title: Deploy a cloud-native ASP.NET Core microservice with GitHub Actions
description: "Not really. Please don't use this lab yet unless you're here because you work with me. It's not done, but I needed to publish it to have something to link to. \U0001F937\U0001F3FB‍♂️"
template:
  repo: microservices-devops-aspnet-core-template
  name: microservices-devops-aspnet-core
  description: Sample files for microservices-devops-aspnet-core
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 00.0_setup.md
    comments:
      - 00.1_steps.md
    data:
      dockerfileUrl: '%payload.repository.html_url%/new/master?filename=action-a/Dockerfile'
steps:
  - title: Setup the environment
    description: Set up your AKS deployment...
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: createIssue
        title: New issue
        body: 01.0_action.md
        comments:
          - 01.1_steps.md
        # Store the url for this new issue using the custom new_issue value
        store: 
          new_issue_url: '{{ result.data.html_url }}'

        # Respond in the issue the user just commented on
      - type: respond
        with: 00.2_response.md
        # Include a `data` object to provide some template variables
        data:
          # Reference the `new_issue` url value from the store
          nextIssueUrl: '{{ store.new_issue_url }}'