title: Deploy a cloud-native ASP.NET Core microservice with GitHub Actions
description: "Not really. Please don't use this lab yet unless you're here because you work with me. It's not done, but I needed to publish it to have something to link to. \U0001F937\U0001F3FB‍♂️"
template:
  repo: microservices-devops-aspnet-core-template
  name: microservices-devops-aspnet-core
  description: Sample files for microservices-devops-aspnet-core
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 00.0_setup.md
    comments:
      - 00.1_steps.md
    data:
      dockerfileUrl: '%payload.repository.html_url%/new/master?filename=action-a/Dockerfile'

steps:
  # 1 - Add a Dockerfile
  - title: Add a Dockerfile
    description: Start your action by creating a Dockerfile
    event: pull_request
    link: "{{ repoUrl }}/issues/1"
    actions:
      - type: gate
        gates:
          - left: "%payload.action%"
            operator: ===
            right: opened
          - left: "%payload.action%"
            operator: ===
            right: synchronize
      - type: getTree
        action_id: tree
        recursive: true
        sha: "%payload.pull_request.head.sha%"
      - type: gate
        left: "%actions.tree.data.tree%"
        operator: includes
        right: path:action-a/Dockerfile
        else:
          type: respond
          with: 01.1_e-no-docker.md
      - type: respond
        with: 01.0_docker-success.md
        data:
          actionAUrl: "%payload.repository.html_url%/new/%payload.pull_request.head.ref%?filename=action-a/entrypoint.sh"
      - type: closeIssue
        issue: Welcome
