title: Deploy a cloud-native ASP.NET Core microservice with GitHub Actions
description: "Not really. Please don't use this lab yet unless you're here because you work with me. It's not done, but I needed to publish it to have something to link to. \U0001F937\U0001F3FB‍♂️"
template:
  repo: microservices-devops-aspnet-core-template
  name: microservices-devops-aspnet-core
  description: Sample files for microservices-devops-aspnet-core
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 00.0_welcome.md
    comments:
      - 00.1_first-steps.md
    data:
      dockerfileUrl: '%payload.repository.html_url%/new/master?filename=action-a/Dockerfile'
steps: []
